name: Lint Go

on:
  workflow_call:
    inputs:
      build-environment:
        description: |
          Environment variables to set when building your binary. Must be separated by newlines.
        required: false
        type: string
        default: ""

permissions:
  contents: write
  pull-requests: write 

jobs:
  run-action:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Compare sizes
        uses: capnspacehook/go-size-tracker@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build-environment: ${{ inputs.build-environment }}

      - name: Test if the graph was created
        id: graph-exists
        run: |
          GRAPH_EXISTS="false"
          if [ -f graph.png ]; then
            GRAPH_EXISTS="true"
          fi
          echo "graph_exists=${GRAPH_EXISTS}" >> "${GITHUB_OUTPUT}"

      - name: Upload graph and comment artifact
        id: upload-artifact
        if: github.event_name == 'pull_request' && steps.graph-exists.outputs.graph_exists == 'true'
        uses: actions/upload-artifact@v5
        with:
          name: graph
          path: |
            graph.png

      - name: Read comment file
        id: comment
        if: github.event_name == 'pull_request'
        run: |
          COMMENT="$(cat comment.txt)"
          {
            echo "COMMENT<<EOF"
            echo "${COMMENT}"
            echo "EOF"
          } >> "${GITHUB_OUTPUT}"

      - name: Create comment with graph
        uses: thollander/actions-comment-pull-request@v3
        if: github.event_name == 'pull_request' && steps.graph-exists.outputs.graph_exists == 'true'
        with:
          message: |
            ${{ steps.comment.outputs.comment }}

            A graph is available here: ${{ steps.upload-artifact.outputs.artifact-url }}
          comment-tag: size-report

      - name: Create comment without graph
        uses: thollander/actions-comment-pull-request@v3
        if: github.event_name == 'pull_request' && steps.graph-exists.outputs.graph_exists == 'false'
        with:
          message: ${{ steps.comment.outputs.comment }}
          comment-tag: size-report
