name: Size report

on:
  workflow_call:
    inputs:
      working-directory:
        description: Relative path to the working directory that should be used to build your binary.
        required: false
        default: "."
        type: string
      build-environment:
        description: Environment variables to set when building your binary. Must be separated by newlines.
        required: false
        default: ""
        type: string
      build-arguments:
        description: |
          Arguments to 'go build' that will build your binary. The binary must be written to a file named 'out'
          in the working directory.
        required: false
        default: '-buildvcs=false -ldflags="-s -w" -trimpath -o out'
        type: string

permissions:
  contents: write
  pull-requests: write 

jobs:
  size-report:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Compare sizes
        uses: capnspacehook/go-size-tracker@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: ${{ inputs.working-directory }}
          build-environment: ${{ inputs.build-environment }}
          build-arguments: ${{ inputs.build-arguments }}

      - name: Test if the graph was created
        id: graph-exists
        if: github.event_name == 'pull_request'
        run: |
          GRAPH_EXISTS="false"
          if [ -f graph.png ]; then
            GRAPH_EXISTS="true"
          fi
          echo "graph_exists=${GRAPH_EXISTS}" >> "${GITHUB_OUTPUT}"

      - name: Upload graph and comment artifact
        id: upload-artifact
        if: github.event_name == 'pull_request' && steps.graph-exists.outputs.graph_exists == 'true'
        uses: actions/upload-artifact@v5
        with:
          name: graph
          path: |
            graph.png

      - name: Read comment file
        id: comment
        if: github.event_name == 'pull_request'
        run: |
          COMMENT="$(cat comment.txt)"
          {
            echo "COMMENT<<EOF"
            echo "${COMMENT}"
            echo "EOF"
          } >> "${GITHUB_OUTPUT}"

      - name: Create comment with graph
        uses: thollander/actions-comment-pull-request@v3
        if: github.event_name == 'pull_request' && steps.graph-exists.outputs.graph_exists == 'true'
        with:
          message: |
            ${{ steps.comment.outputs.comment }}

            A graph is available here: ${{ steps.upload-artifact.outputs.artifact-url }}
          comment-tag: size-report

      - name: Create comment without graph
        uses: thollander/actions-comment-pull-request@v3
        if: github.event_name == 'pull_request' && steps.graph-exists.outputs.graph_exists == 'false'
        with:
          message: ${{ steps.comment.outputs.comment }}
          comment-tag: size-report
